### PR TITLE
Spanish translation add

### PR DESCRIPTION
**Pull request by 41646F6C666F**
As asked by the issue #17 to add languages.
Here's come the Spanish translation strings; non-breaking change PR.

Update needed in https://github.com/TechWiz-3/who-unfollowed-me/issues/17#issue-1402113560.

EDIT: 
As this repo is active in the Hacktoberfest 2022,
please add the tag `hacktoberfest-accepted` to this issue if you accept and merge it.

### CODE REVIEW

**Comment by TechWiz-3** [comment]
You speak French and Spanish fluently? 😮

**Comment by 41646F6C666F** [comment]
Yes @TechWiz-3, and I have degrees in both languages 😉

**Comment by TechWiz-3** [comment]
Thank you sir

**Comment by 41646F6C666F** [comment]
You are welcome @TechWiz-3. 

But don't forget to add the label `hacktoberfest-accepted` to this Pull Request, and the others valid ones.
Without that, yourself and the contributors won't be getting any point for the Hacktoberfest 😉

**Comment by TechWiz-3** [comment]
Maintainers get points for hacktoberfest?

**Comment by 41646F6C666F** [comment]
:trollface: 
Yes, like If you add the label `hacktoberfest-accepted` to the issues as I told you.

All the best 😉

**Pull request merged**
