### PR TITLE
French translation fix

### PR DESCRIPTION
**Pull request by 41646F6C666F**
Minor fixing of the French translation, as in some parts it's just literal translation and nonsense.
Most likely, the French translation was done used some kind of automatic translation and without any knowledge of the language.

Don't forget to review the pull/merge requests and adding the correct label to them, your participation will be calculated from there @TechWiz-3.
For example, the PR #23 doesn't follow the guidelines of the Hacktoberfest, and shouldn't be tagged `hacktoberfest-accepted` but tagged `invalid`. You have also many others, like this actual one, where you can apply the tag `hacktoberfest-accepted`, have fun :shipit:

### CODE REVIEW

**Comment by TechWiz-3** [comment]
Wow ok. First of all thanks a lot for fixing up the French translation, since I don't speak French I simply didn't know.

> For example, the PR https://github.com/TechWiz-3/who-unfollowed-me/pull/23 doesn't follow the guidelines of the Hacktoberfest, and shouldn't be tagged

Which guideline do they violate? Please provide the Hacktoberfest guideline name.

> like this actual one, where you can apply the tag hacktoberfest-accepted, have fun

The `hacktoberfest-accepted` label is un-necessary for this repo, I have it only because some ppl want it anyway! How come you know all about the guidelines but about that?

**Comment by 41646F6C666F** [comment]
# Content
I normally work on code, but since Hacktoberfest started I've seen so many bad translations, so now I'm mostly looking to provide good quality translation/localization content on the projects I find interesting or fun. 
That's also one of the points of the Hacktoberfest:

> We’re committed to prioritizing quality contributions as outlined in our participation rules.

 You can read more about [here](https://hacktoberfest.com/participation/).

# Participation

About the `hacktoberfest-accepted` tag/label, indeed it's totally unnecessary for the repo. 
But it is needed for the issues in order for the Hacktoberfest scanner to link the issues to the contributors and maintainer, in order for them to get their participation points too:

> Be ready to review pull/merge requests, accepting those that are valid by merging them, leaving an overall approving review, or by adding the “hacktoberfest-accepted” label.
> Reject any spammy requests you receive by labeling them as “spam,” and any other invalid contributions by closing them or labeling them as “invalid.”

Read more about on the [Maintainers](https://hacktoberfest.com/participation/#maintainers) section of the participation page.

**Comment by TechWiz-3** [comment]
You still haven't told me why i should mark #23 invalid

**Comment by 41646F6C666F** [comment]
Only if you applied previously the tag `hacktoberfest-accepted` to that issue to invalidate it.

**Pull request merged**
