### PR TITLE
Update unfollow.py to check if a user no longer exists 

### PR DESCRIPTION
**Pull request by Lyeriff**

### CODE REVIEW

**Comment by TechWiz-3** [comment]
Niceee 🔥 

One change please:

`result+="[deleted]"` -> `result = f"{result} [deleted]"` - just a personal preference

**Comment by Lyeriff** [comment]
> Niceee 🔥
> 
> One change please:
> 
> `result+="[deleted]"` -> `result = f"{result} [deleted]"` - just a personal preference

Sure! I've changed as you proposed, please review.

**Comment by TechWiz-3** [comment]
Sorry to request changes again 😅 i didn't pay proper attention the first time

Since the 'link' is built from `result` when we add `[deleted]` to result it also gets added to the link when it's built.
`result=f"{result} [deleted]"` is perfect, but let's make another variable before that line that's something like `result_for_link = result`
And then below that change `unfollowers.append((result,f"https://github.com/{result}/"))` -> `unfollowers.append((result,f"https://github.com/{result_for_link}/"))`

One other change... for those using tokens please change the request to include `headers=HEADERS` [line `104`]

**Comment by Lyeriff** [comment]
Oh yeah, my bad I'll fix the issues.

**Comment by TechWiz-3** [comment]
Perfecto, thanks a lot and congrats on your first PR 🥳 🥳

**Comment by TechWiz-3** [comment]
Little tip for the future, when you submit a PR that solves the issue, consider a little message in the description like `Solves #<issue num>` 😁

**Comment by Lyeriff** [comment]
> Little tip for the future, when you submit a PR that solves the issue, consider a little message in the description like `Solves #<issue num>` 😁

Thanks for guiding me.
And sorry for not mentioning issue. I did the same thing just now, sent a PR to one more repo without the issue or without getting assigned, and the maintainer got annoyed 😭.

**Comment by TechWiz-3** [comment]
Nahhhh issok man not a problem at all, just a little tip :))

**Comment by Lyeriff** [comment]
> Nahhhh issok man not a problem at all, just a little tip :))

okk thanks! also just wondering if you could add the hacktoberfest-accepted lable to this PR.

**Comment by TechWiz-3** [comment]
Sure I can, but i don't think that's necessary coz i already have the `hacktoberfest` tab on the repo

**Pull request merged**
