### PR TITLE
Local Development Environment and add Versioning

### PR DESCRIPTION
**Pull request by k1m0ch1**
# Description
I made a local development environment possible with this repo

## Type of change
- add .gitignore with pipenv tools (only needs requirements.txt)
- update `HACKING.md` and `README.md` to explain the local development and testing
- update `requirements.txt` with a proper library that needs for the tools
- update `setup.py` so the directory path will working
- update some source to add `versioning`

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested
- manually running the program using the command `python setup.py develop` so it will install on the local machine, if this working try running the command `which unfollow` and it will return the path binary app
image
- try running the command `unfollow` if working you can see the change
image

# Checklist:

- [x] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by k1m0ch1** [comment]
please review this @TechWiz-3

**Comment by TechWiz-3** [comment]
WOW this is amazing, thank you brother.

Some questions:
1. Why did you change the package dir from `src/unfollow` to `src`? Any specific reason?
2. What happens if the specified versions in `requirements.txt` conflict with the dependency versions of other packages?
3. Will `python3 setup.py develop` need to be made after every change to a local file? Or does it only have to be done once?
4. Do you recommend any centralised way to bump versions in `versions.py` and `setup.py` at the same time?

[time to sleep now :) will get back when i wake up]

**Comment by k1m0ch1** [comment]
Hi, @TechWiz-3 

1. which part I change the package dir from `src/unfollow` to `src` ? from `setup.py`
2. the static version is better thank using the latest/newest version because we didn't know about the break change, but from this case actually its not a problem since the `requests` and `beautifier` module only used for API and parse, so this mean both cases will never make any break change.
3. well I give a very specific reason why `python setup.py develop` need to run, because this will test the local development of CLI before goes to public, so every PR will always have test right, they need to make sure to run this first.
4. ah right, I forgot about the `setup.py` I will change is to same with other

**Comment by k1m0ch1** [comment]
@TechWiz-3 done fixed the point 4, could you please check again

**Comment by TechWiz-3** [comment]
Thank you!

> 3\. well I give a very specific reason why `python setup.py develop` need to run, because this will test the local development of CLI before goes to public, so every PR will always have test right, they need to make sure to run this first.

So after using `python3 setup.py develop`, how can you undo using the local development?

**Comment by k1m0ch1** [comment]
> So after using python3 setup.py develop, how can you undo using the local development?

@TechWiz-3 ah do you mean by virtual environment, I'm using pipenv much easier so I only need to get out the environment.

**Comment by k1m0ch1** [comment]
hi @TechWiz-3 should I resolve the conflict or I shouldn't continue this, since you could approve other PR and can't approve this, maybe it will be better if I can decide on continue with this or not.

**Comment by TechWiz-3** [comment]
Ah thanks for following up, I was just going to message about this. You opened my eyes a lot to other ways of managing the development environment. I decided to go with poetry instead of the setup.py build solution but thanks a lot.

If you wish to make a separate PR with the `version.py` and `requirements.txt` changes I will accept them 🙏

**Comment by k1m0ch1** [comment]
thanks for the follow up, I will close this PR and makes a new PR

**Pull request closed without merging**
