### PR TITLE
Update unfollow.py

### PR DESCRIPTION
**Pull request by TimTemi**
Commented

# Description
> Put changes made - link an issue if relevant

## Type of change

> Please delete options that are not relevant. For the item that is relevant mark it completed as `- [x] text here`

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
> E.g.
- manually running the program on the localhost

# Checklist:

> Mark as completed `- [x] text here`

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by TechWiz-3** [comment]
C'mon is that seriously the best you can do? Adding a single comment to a single file?
And your comment isn't formatted properly you make it all lowercase and put a space between the `#` and the text.

I appreciate wanting to contribute and participate in Hacktoberfest but it's becoming tedious as a maintainer reviewing PRs with literally no added value.

If you wish me to accept this PR, add another 20 comments and make sure your changes don't fail the checks. You can test this with `poetry run black` or `poetry run flake8` after installing the development environment as specified in the `CONTRIBUTING.md`

**Comment by TimTemi** [comment]
@TechWiz-3 , Sorry you have to go through every PR, with no value added. Yeap, my first time contributing to Open source project, I guess the YouTube tutorial didn't teach me better, indeed one can also learn through contributing to open source projects. I just learned how to actually comment out a line. Thank you 😊

**Comment by TechWiz-3** [comment]
Oh, the 'checks' I'm talking about are these
Screen Shot 2022-10-25 at 3 46 04 pm

They automatically check the codebase for style errors that make the code harder to read. In this case they failed because the comment you added doesn't confirm to the style guide.

If you click the `Details` link on the 4th check `Linting / flake8 (3.10) (pull_request)` and look in the [logs](https://github.com/TechWiz-3/who-unfollowed-me/actions/runs/3314533939/jobs/5481559592) you can see.
```
./unfollow/unfollow.py:64:1: E265 block comment should start with '# '
./unfollow/unfollow.py:65:1: E302 expected 2 blank lines, found 1
```
Info on linting: https://www.perforce.com/blog/qac/what-lint-code-and-why-linting-important
Info on GitHub Actions: https://www.youtube.com/watch?v=R8_veQiYBjI

**Comment by TimTemi** [comment]
@TechWiz-3 , I guess I still have a lot to learn. I'll watch the tutorial, thanks for sharing😊, encountering mistakes and learning through them. I'm sorry it had to be project. I'll delete the commit and anything connected to it.

**Comment by TechWiz-3** [comment]
that's alright, don't worry about it

i admire your perseverance, keep at it 🔥

**Comment by TimTemi** [comment]
Thanks

**Pull request closed without merging**
