### PR TITLE
Cache last week

### PR DESCRIPTION
**Pull request by tintinthong**
Issue https://github.com/TechWiz-3/who-unfollowed-me/issues/6

### CODE REVIEW

**Comment by TechWiz-3** [comment]
Thank you 🙏, will review this when I get home tonight

**Comment by TechWiz-3** [comment]
I'm getting an error when running `NameError: name 'cached' is not defined`

Full traceback:

```py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Peregrine/Desktop/Projects/forks/tests/tintin-unfollow/unfollow/cli.py", line 218, in main
    get_links()
  File "/Users/Peregrine/Desktop/Projects/forks/tests/tintin-unfollow/unfollow/cli.py", line 98, in get_links
    info = unfollow_main()
  File "/Users/Peregrine/Desktop/Projects/forks/tests/tintin-unfollow/unfollow/unfollow.py", line 268, in main
    return unfollowed_future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/Peregrine/Desktop/Projects/forks/tests/tintin-unfollow/unfollow/unfollow.py", line 233, in run_unfollow
    unfollows_last_week = get_unfollows_since(unfollows, 7) if cached else []
NameError: name 'cached' is not defined```

**Comment by tintinthong** [comment]
> I'm getting an error when running `NameError: name 'cached' is not defined`
> 
> Full traceback:
> 
> ```python
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/Peregrine/Desktop/Projects/forks/tests/tintin-unfollow/unfollow/cli.py", line 218, in main
>     get_links()
>   File "/Users/Peregrine/Desktop/Projects/forks/tests/tintin-unfollow/unfollow/cli.py", line 98, in get_links
>     info = unfollow_main()
>   File "/Users/Peregrine/Desktop/Projects/forks/tests/tintin-unfollow/unfollow/unfollow.py", line 268, in main
>     return unfollowed_future.result()
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 433, in result
>     return self.__get_result()
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
>     raise self._exception
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/Users/Peregrine/Desktop/Projects/forks/tests/tintin-unfollow/unfollow/unfollow.py", line 233, in run_unfollow
>     unfollows_last_week = get_unfollows_since(unfollows, 7) if cached else []
> NameError: name 'cached' is not defined```
> ```

Whoops sorry. I fixed the bug. 

There was also another bug here 
[624758e](https://github.com/TechWiz-3/who-unfollowed-me/pull/33/commits/624758e5ec04342383035221a75d5d8787269420)

**Comment by TechWiz-3** [comment]
Ah cool

**Comment by TechWiz-3** [comment]
yup i noticed lol, it can be another hacktoberfest issue for the translators

**Comment by TechWiz-3** [comment]
I don't mind the messy output but I'm not getting the expected behaviour.

Expected: after detecting unfollowers, the next run will display the unfollowers previously displayed

### Reality: 
#### Detection of unfollowers:
Screen Shot 2022-10-13 at 9 27 59 pm
(Ignore the dodgy names please 🤣)

#### Run after that - does not display previously displayed unfollowers:
Screen Shot 2022-10-13 at 9 28 12 pm

**Comment by TechWiz-3** [comment]
Ok this is because `cached` was never assigned

**Comment by TechWiz-3** [comment]
Ok thanks for your work, I'll clean up the output and then merge

**Comment by tintinthong** [comment]
> Ok this is because `cached` was never assigned

Ahhhhhhhhh makes sense

**Comment by TechWiz-3** [comment]
Thanks a lot for your work

Just a tip for the future, you did a lot of really nice programming and you're definitely more knowledgeable technically then i am, when you submit the PR make sure that you clean up the output and finer details so all your good work comes through 👌

**Pull request merged**
