### PR TITLE
updated tamil script

### PR DESCRIPTION
**Pull request by rexdivakar**
# Description
> Put changes made - link an issue if relevant

## Type of change

> Please delete options that are not relevant. For the item that is relevant mark it completed as `- [x] text here`

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
> E.g.
- manually running the program on the localhost

# Checklist:

> Mark as completed `- [x] text here`

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by rexdivakar** [comment]
Issue #21 is also added with this PR fix, kindly validate and merge the PR with hacktoberfest tags

**Comment by TechWiz-3** [comment]
The Tamil translation is fine however you have also:

1. Half completed/fixed #21 
     1. However you haven't adjusted the `README.md` appropriately
3. Added classifiers
     1. The license classifier is incorrect
     2. The Intended Audience should be Developers not Education
     4. Operating System tags should also be Linux and OSX

In the future, please either make a PR for every change or list all the changes you made in the PR description and describe the PR appropriately ;) 👍 

For now, either remove the Pypi changes OR complete and fix the Pypi changes and I'll merge

**Comment by rexdivakar** [comment]
I have fixed all the issues, kindly recheck

**Comment by TechWiz-3** [comment]
Thank you

**Comment by rexdivakar** [comment]
Pls add hacktoberfest labels to the PR

**Pull request merged**
