### PR TITLE
🐛 FIX: Add config versioning to future-proof against format change

### PR DESCRIPTION
**Pull request by Dinoosawruss**
# Description
> Put changes made - link an issue if relevant
Added config versioning as discussed in issue #37 

## Type of change

> Please delete options that are not relevant. For the item that is relevant mark it completed as `- [x] text here`

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
- manually running the program on the localhost

# Checklist:

> Mark as completed `- [x] text here`

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by TechWiz-3** [comment]
Wow this is a really neat solution, appreciate your work, thanks 🙏

**Comment by Dinoosawruss** [comment]
Noticed there are some merge conflicts will sort those later

**Comment by TechWiz-3** [comment]
i was going to resolve them but if you do that would be much appreciated

**Comment by Dinoosawruss** [comment]
Ah seems like I'm not allowed to resolve the conflicts because I don't have write access to this repo

**Comment by TechWiz-3** [comment]
gotta say, i love this solution so much 🔥

**Pull request merged**
