### PR TITLE
Added for Hindi

### PR DESCRIPTION
**Pull request by ShivanshDengla**
# Description
> Put changes made - link an issue if relevant

## Type of change

> Please delete options that are not relevant. For the item that is relevant mark it completed as `- [x] text here`

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
> E.g.
- manually running the program on the localhost

# Checklist:

> Mark as completed `- [x] text here`

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by ShivanshDengla** [comment]
Hey,
I updated for Hindi, but i am doing this for the first time so i didn;t know how to correctly code it. I just copied english and changed the Hindi lines, do let me know if theres any mistake, i'll try to correct it.
Thanks

**Comment by TechWiz-3** [comment]
This is perfect except please remove line `52` `locale = "hindi"`. Otherwise everything is perfect.

The `locale = <language>` statement is for the user to configure which language they want to see i.e. English or Hindi

**Comment by ShivanshDengla** [comment]
> This is perfect except please remove line `52` `locale = "hindi"`. Otherwise everything is perfect.
> 
> The `locale = <language>` statement is for the user to configure which language they want to see i.e. English or Hindi

Hey,
Thanks for the comment,  i removed line 52.
Thanks.

**Comment by TechWiz-3** [comment]
Nah this is perfect brother. Congrats ;)

**Comment by ShivanshDengla** [comment]
> Nah this is perfect brother. Congrats ;)

ok thanks, do you need to put hacktober accepted label here, or its fine?

**Comment by TechWiz-3** [comment]
I can but it's not necessary because the repo has the `hacktoberfest` topic on it. Some people like it so that's why I have it

**Comment by ShivanshDengla** [comment]
Thank you so much.

**Comment by TechWiz-3** [comment]
All good man :)

**Pull request merged**
