### PR TITLE
Translation(config): Improved Hindi Translation

### PR DESCRIPTION
**Pull request by kailashchoudhary11**
# Description
> Put changes made - link an issue if relevant

## Type of change

> Please delete options that are not relevant. For the item that is relevant mark it completed as `- [x] text here`

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
> E.g.
- manually running the program on the localhost

# Checklist:

> Mark as completed `- [x] text here`

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by TechWiz-3** [comment]
Thanks a lot for your work, I trust you however since this is editing a translation and I do not understand Hindi, I will ask some fluent people to review the changes first to ensure the quality is in fact being improved 👍

**Comment by kailashchoudhary11** [comment]
> Thanks a lot for your work, I trust you however since this is editing a translation and I do not understand Hindi, I will ask some fluent people to review the changes first to ensure the quality is in fact being improved 👍

Okay Sure!!

**Comment by Villain45** [comment]
@TechWiz-3 what he changed is perfect in Hindi

**Comment by TechWiz-3** [comment]
Thanks a lot @Villain45 for the feedback and once again @kailashchoudhary11 thanks for your work 😊

**Comment by kailashchoudhary11** [comment]
> Thanks a lot @Villain45 for the feedback and once again @kailashchoudhary11 thanks for your work 😊

Thank you @TechWiz-3

**Pull request merged**
